### ISSUE TITLE
g++: error: unrecognized command line option ‘-std=c++14’

### ISSUE THREAD

**Issue by madzafv** [nedaz/kraken#5]
I'm trying to install kraken but getting this error. I checked my g++ version and it should recognize -std=c++14. 
Also using cmake version 3.10.3.
What could be wrong?
thanks!
> -bash-4.2$ make
> [  0%] Building CXX object CMakeFiles/RunKraken.dir/ryggrad/src/general/AlignmentBlock.cc.o
> g++: error: unrecognized command line option ‘-std=c++14’
> make[2]: *** [CMakeFiles/RunKraken.dir/ryggrad/src/general/AlignmentBlock.cc.o] Error 1
> make[1]: *** [CMakeFiles/RunKraken.dir/all] Error 2
> make: *** [all] Error 2
> -bash-4.2$ which g++
> /opt/gcc-7.3.0/gcc-7.3.0/bin/g++
> -bash-4.2$ g++ --version
> g++ (GCC) 7.3.0
> Copyright (C) 2017 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.  There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
> -bash-4.2$ cmake --version
> cmake version 3.10.3
> CMake suite maintained and supported by Kitware (kitware.com/cmake).

**Comment by madzafv** [comment]
Just an update that I seem to have successfully compiled the program using std=c++11

**Comment by nedaz** [comment]
Your CMake is likely using a version of g++ that doesn't support c++14. I suggest you check that.
